version: '3'

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: always

  db:
    container_name: db
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    restart: always
  
  mongo-data:
    build: ./mongo-data
    depends_on:
      - db